<?php

namespace WonderWp\Plugin\Generator\Generator\Theme\Block;

use WonderWp\Plugin\Generator\Generator\Theme\Classic\ClassicThemeGenerator;

class BlockThemeGenerator extends ClassicThemeGenerator
{
    protected function createBaseFolders(array $folders = [])
    {
        return parent::createBaseFolders($folders); // TODO: Change the autogenerated stub
    }

}